### ISSUE TITLE
Error while using the support-logging-client

### ISSUE THREAD

**Issue by jay11ca39** [edgexfoundry/support-logging-client#5] opened 2017-08-29 09:25 UTC
I was trying to use support-logging-client SDK but facing some problem.

Following are the steps I followed:
1. Created a sample maven application in Eclipse IDE. 

2. Included the following lines in sample's pom.xml:
```
<dependency>
<groupId>org.edgexfoundry</groupId>
<artifactId>support-logging-client</artifactId>
<version>1.0.0-SNAPSHOT</version>
</dependency>
```

3. Included following in my sample application:
```
private final static EdgeXLogger logger = EdgeXLoggerFactory.getEdgeXLogger(App.class);
public static void main( String[] args ) {
logger.info("Testing is successful");
}
```

4. Ran sample application as java application.

I got the following error:-

**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.**

**System information:**
Windows 7 [64-bit]
Eclipse Oxygen

**Comment by trcox** [comment] 2017-08-29 14:31
Were you able to successfully run a maven install on the application? That dependency should get resolved when the support-logging-client artifact gets pulled in.

**Comment by jpwhitemn** [comment] 2017-08-29 21:12
This is actually not a bug.  Your project needs an SLF4J implementation.  In other microservices, like core-metadata, core-data, etc. the use of Spring Boot adds the implementation of SLF4J through inclusion of Spring Boot to the project.  In the case of a simple basic application, you'll need to specify the addition of SLF4J implementation along with the support logging client.  See https://www.slf4j.org/codes.html for more details.  As an example, here would be a bare bones pom.xml including the logging client and simple SLF4J package to do this and have the issue resolved in your application.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.dell</groupId>
	<artifactId>foo</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<support-logging-client.version>1.0.0-SNAPSHOT</support-logging-client.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.edgexfoundry</groupId>
			<artifactId>support-logging-client</artifactId>
			<version>${support-logging-client.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.8.0-alpha2</version>
		</dependency>
	</dependencies>
</project>

**Closed by jpwhitemn** 2017-08-29 21:12 UTC
